### ISSUE TITLE
value=nan error

### ISSUE THREAD

**Issue by yassersouri** [rewonc/pastalog#12]
Salam

In deep learning sometimes the loss diverges to infinity which results in loss becoming nan.

This results in an exception in the python code:
`HTTPError: 400 Client Error: Bad Request for url: http://localhost:8100/data`

Also the error in the node server:

```
SyntaxError: Unexpected token N
    at Object.parse (native)
    at parse (/home/yasser/.virtualenvs/sci/lib/python2.7/site-packages/pastalog/node_modules/body-parser/lib/types/json.js:88:17)
    at /home/yasser/.virtualenvs/sci/lib/python2.7/site-packages/pastalog/node_modules/body-parser/lib/read.js:116:18
    at invokeCallback (/home/yasser/.virtualenvs/sci/lib/python2.7/site-packages/pastalog/node_modules/raw-body/index.js:262:16)
    at done (/home/yasser/.virtualenvs/sci/lib/python2.7/site-packages/pastalog/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/home/yasser/.virtualenvs/sci/lib/python2.7/site-packages/pastalog/node_modules/raw-body/index.js:308:7)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by rewonc** [comment]
Oops! This is a pretty silly error -- thanks for catching it. Will fix this is the next patch.
