### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by InnovArul** [rewonc/pastalog#22]
I am using NPM version v7.9.0.
I am facing the following error while running `npm run build` for pastalog.
could you please let me know how to resolve this?

```
-> % npm run build    

> pastalog@1.0.4 build /media/data/arul/miscellanous/pastalog
> webpack

(node:22322) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 7f2522d0b30b7d93f2acefee6480ee97bc23e1e6dcc1ef502acc1bbb5073
Version: webpack 2.4.1
Child
    Hash: 7f2522d0b30b7d93f2ac
    Time: 2380ms
                    Asset     Size  Chunks             Chunk Names
    ./build/assets/app.js  4.17 kB       0  [emitted]  main
       [0] ./src/client.js 1.53 kB {0} [built] [failed] [1 error]
    
    ERROR in ./src/client.js
    Module build failed: Error: Couldn't find preset "es2015-webpack" relative to directory "/media/data/arul/miscellanous/pastalog/src"
        at /media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (native)
        at OptionManager.resolvePresets (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/media/data/arul/miscellanous/pastalog/node_modules/babel-loader/lib/index.js:46:20)
        at Object.module.exports (/media/data/arul/miscellanous/pastalog/node_modules/babel-loader/lib/index.js:163:20)
Child
    Hash: efee6480ee97bc23e1e6
    Time: 2360ms
                Asset     Size  Chunks             Chunk Names
    ./build/server.js  4.17 kB       0  [emitted]  main
       [0] ./src/server.js 1.53 kB {0} [built] [failed] [1 error]
    
    ERROR in ./src/server.js
    Module build failed: Error: Couldn't find preset "es2015-webpack" relative to directory "/media/data/arul/miscellanous/pastalog/src"
        at /media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (native)
        at OptionManager.resolvePresets (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/media/data/arul/miscellanous/pastalog/node_modules/babel-loader/lib/index.js:46:20)
        at Object.module.exports (/media/data/arul/miscellanous/pastalog/node_modules/babel-loader/lib/index.js:163:20)
Child
    Hash: dcc1ef502acc1bbb5073
    Time: 2357ms
                    Asset     Size  Chunks             Chunk Names
    ./test/build/index.js  4.17 kB       0  [emitted]  main
       [0] ./test/index.js 1.54 kB {0} [built] [failed] [1 error]
    
    ERROR in ./test/index.js
    Module build failed: Error: Couldn't find preset "es2015-webpack" relative to directory "/media/data/arul/miscellanous/pastalog/test"
        at /media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
        at Array.map (native)
        at OptionManager.resolvePresets (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
        at OptionManager.mergePresets (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
        at OptionManager.mergeOptions (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
        at OptionManager.init (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
        at File.initOptions (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/index.js:212:65)
        at new File (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/file/index.js:135:24)
        at Pipeline.transform (/media/data/arul/miscellanous/pastalog/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
        at transpile (/media/data/arul/miscellanous/pastalog/node_modules/babel-loader/lib/index.js:46:20)
        at Object.module.exports (/media/data/arul/miscellanous/pastalog/node_modules/babel-loader/lib/index.js:163:20)

npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/home/arul/.nvm/v7.9.0/bin/node" "/home/arul/.nvm/v7.9.0/bin/npm" "run" "build"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pastalog@1.0.4 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the pastalog@1.0.4 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pastalog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pastalog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pastalog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arul/.npm/_logs/2017-04-23T19_07_24_649Z-debug.log

```

**Comment by wojtekcz** [comment]
I don't know if it's right way of fixing it or not but if in the file webpack.config.js you'll replace all occurences of 'es2015-webpack' with 'es2015', the 'npm run build' command will succeed.

**Comment by kenkit** [comment]
This is a bug that needs fixing
